-- Allow inserting explicit IDs during one-time data migration (preserves
-- existing buyer IDs so buyer_activity.buyer_id foreign keys stay valid).
alter table buyers          alter column id set generated by default;
alter table facebook_posts  alter column id set generated by default;
alter table buyer_activity  alter column id set generated by default;
